// Code generated by "stringer -type=Error"; DO NOT EDIT.

package spice

import "fmt"

const _Error_name = "RedErrorOKRedErrorErrorRedErrorInvalidMagickRedErrorInvalidDataRedErrorVersionMismatchRedErrorNeedSecuredRedErrorNeedUnsecuredRedErrorPermissionDeniedRedErrorBadConnectionIDRedErrorChannelNotAvailable"

var _Error_index = [...]uint8{0, 10, 23, 44, 63, 86, 105, 126, 150, 173, 200}

func (i Error) String() string {
	if i >= Error(len(_Error_index)-1) {
		return fmt.Sprintf("Error(%d)", i)
	}
	return _Error_name[_Error_index[i]:_Error_index[i+1]]
}
