// Code generated by "stringer -type=Info"; DO NOT EDIT.

package spice

import "fmt"

const _Info_name = "RedInfoGeneral"

var _Info_index = [...]uint8{0, 14}

func (i Info) String() string {
	if i >= Info(len(_Info_index)-1) {
		return fmt.Sprintf("Info(%d)", i)
	}
	return _Info_name[_Info_index[i]:_Info_index[i+1]]
}
