// Code generated by "stringer -type=Warn"; DO NOT EDIT.

package spice

import "fmt"

const _Warn_name = "RedWarnGeneral"

var _Warn_index = [...]uint8{0, 14}

func (i Warn) String() string {
	if i >= Warn(len(_Warn_index)-1) {
		return fmt.Sprintf("Warn(%d)", i)
	}
	return _Warn_name[_Warn_index[i]:_Warn_index[i+1]]
}
